# Generated by Django 3.1.1 on 2020-12-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_task',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
